version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/tkuchiki/kubectl-setimg/cmd.Version={{.Version}} -X github.com/tkuchiki/kubectl-setimg/cmd.GitCommit={{.Commit}} -X github.com/tkuchiki/kubectl-setimg/cmd.GitTag={{.Tag}}
    binary: kubectl-setimg

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: tkuchiki
    name: kubectl-setimg
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## What's Changed
    
    This release includes bug fixes and improvements.
  footer: |
    ## Docker Images
    
    Docker images are available at:
    - `ghcr.io/tkuchiki/kubectl-setimg:{{.Tag}}`
    - `ghcr.io/tkuchiki/kubectl-setimg:latest`

# Generate completion scripts
nfpms:
  - id: kubectl-setimg
    package_name: kubectl-setimg
    vendor: Takuya Kuchiki
    homepage: https://github.com/tkuchiki/kubectl-setimg
    maintainer: Takuya Kuchiki <tkuchiki@example.com>
    description: kubectl plugin for updating container images with interactive selection
    license: Apache 2.0
    formats:
      - deb
      - rpm
    contents:
      - src: ./kubectl-setimg
        dst: /usr/local/bin/kubectl-setimg
        file_info:
          mode: 0755